name: Deploy in github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

      - name: print variable
        run: echo "La variable es ${{ secrets.MI_VARIABLE }}"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test

      - name: Build page
        run: npm run build
