name: Deploy in github pages

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

      - name: print variable
        run: echo "La variable es ${{ secrets.MI_VARIABLE }}"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test

      - name: Build page
        run: npm run build

      - name: Upload artifact
        # se hace deploy usando la acción de GitHub Pages
        # https://github.com/marketplace/actions/upload-github-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  Deploy:
    # se hara el deploy usando https://github.com/marketplace/actions/deploy-github-pages-site
    runs-on: ubuntu-latest
    needs: Build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment-pages
        uses: actions/deploy-pages@v4
